create database tes1
use tes1
CREATE TABLE TAIKHOAN(
	TaiKhoan nvarchar(50) not null,
	MatKhau nvarchar(50) not null
)
INSERT INTO TAIKHOAN (TaiKhoan, MatKhau) 
VALUES 
('admin', '123'),
('MNV001', '123456'),
('QL001', '123456'),
('MNV002', '123456');


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[XEMAY](
	MaXe nvarchar(10) not null,
	TenXe nvarchar(20)  null,
	LoaiXe nvarchar(10)  null,
	SoKhung nvarchar(10)  null,
	SoMay nvarchar(10)  null,
	BienSo nvarchar(10) null,
	MaMau nvarchar(10)  null,
PRIMARY KEY CLUSTERED 
(
	[MaXe] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[YEUCAUSUACHUA](
	MaSuaChua nvarchar(10) not null,
	MaXe nvarchar(10) not null,
	MaKhachHang nvarchar(10) not null,
	NgaySua date  null,
	NguyenNhan nvarchar(100) null,
PRIMARY KEY CLUSTERED 
(
	MaSuaChua asc
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	MaKhachHang nvarchar(10) not null,
	TenKhachHang nvarchar(20) not null,
	DiaChi nvarchar(20) null,
	SoDienThoai nvarchar(10) null,
PRIMARY KEY CLUSTERED 
(
	MaKhachHang asc
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[HOADON](
	[MaHoaDon] [nvarchar](10) NOT NULL,
	[MaNhanVien] [nvarchar](10) NOT NULL,
	[MaPhuTung] [nvarchar](10) NOT NULL,
	[MaKhachHang] [nvarchar](10) NOT NULL,
	[NgayIn] [date] NOT NULL,
	[GiaiPhap] [nvarchar](100) NOT NULL,
	[SoLuong] [int] NULL,
	[TongTien] [money] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaHoaDon] ASC,
	[MaPhuTung] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



CREATE TABLE [dbo].[PHUTUNG](
	MaPhuTung nvarchar(10) not null,
	TenPhuTung NVARCHAR(30),
	SoLuong int  null,
	DonGiaNhap money null,
	DonGiaBan money  null,
PRIMARY KEY CLUSTERED 
(
	MaPhuTung asc
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETHDN](
	MaHDN nvarchar(10) not null,
	MaPhuTung nvarchar(10) not null,
	SoLuongNhap int  null,

PRIMARY KEY CLUSTERED 
(
	MaHDN asc,
	MaPhuTung asc
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADONNHAPPHUTUNG](
	MaHDN nvarchar(10) not null,
	NgayNhap date not null,
	MaNhanVien nvarchar(10) not null,
	TongTien money null,
PRIMARY KEY CLUSTERED 
(
	MaHDN asc
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MaNhanVien] [nvarchar](10) NOT NULL,
	[TenNhanVien] [nvarchar](30) NULL,
	[MaTrinhDo] [nvarchar](10) NOT NULL,
	[NgaySinh] [date] NOT NULL,
	[GioiTinh] [nvarchar](10) NULL,
	[SoDienThoai] [nvarchar](15) NULL,
	[NgayBatDau] [date] NULL,
	[DiaChi] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNhanVien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRINHDO](
	MaTrinhDo nvarchar(10) not null,
	TenTrinhDo nvarchar(10) not null,
PRIMARY KEY CLUSTERED 
(
	MaTrinhDo asc
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[YEUCAUSUACHUA]  WITH CHECK ADD  CONSTRAINT [FK_2] FOREIGN KEY([MaXe])
REFERENCES [dbo].[XEMAY] ([MaXe])
GO
ALTER TABLE [dbo].[YEUCAUSUACHUA]  WITH CHECK ADD  CONSTRAINT [FK_3] FOREIGN KEY([MaKhachHang])
REFERENCES [dbo].[KHACHHANG] ([MaKhachHang])
GO

ALTER TABLE [dbo].[CHITIETHDN]  WITH CHECK ADD  CONSTRAINT [FK_8] FOREIGN KEY([MaPhuTung])
REFERENCES [dbo].[PHUTUNG] ([MaPhuTung])
GO
ALTER TABLE [dbo].[CHITIETHDN]  WITH CHECK ADD  CONSTRAINT [FK_9] FOREIGN KEY([MaHDN])
REFERENCES [dbo].[HOADONNHAPPHUTUNG] ([MaHDN])
GO
ALTER TABLE [dbo].[HOADONNHAPPHUTUNG]  WITH CHECK ADD  CONSTRAINT [FK_10] FOREIGN KEY([MaNhanVien])
REFERENCES [dbo].[NHANVIEN] ([MaNhanVien])
GO
ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_11] FOREIGN KEY([MaTrinhDo])
REFERENCES [dbo].[TRINHDO] ([MaTrinhDo])
GO
ALTER TABLE KHACHHANG
ALTER COLUMN TenKhachHang NVARCHAR(20);
ALTER TABLE KHACHHANG
ALTER COLUMN DiaChi NVARCHAR(50);
go
ALTER TABLE TRINHDO
ALTER COLUMN TenTrinhDo NVARCHAR(30);
INSERT INTO TRINHDO(MaTrinhDo, TenTrinhDo) VALUES ('TD01', N'thợ sửa');
INSERT INTO TRINHDO(MaTrinhDo, TenTrinhDo) VALUES ('TD02', N'quản lý');
INSERT INTO TRINHDO(MaTrinhDo, TenTrinhDo) VALUES ('TD03', N'kế toán');
UPDATE TRINHDO
SET TenTrinhDo = N'thợ sửa bậc 1'
WHERE MaTrinhDo = N'TD01';
UPDATE TRINHDO
SET TenTrinhDo = N'thợ sửa bậc 2'
WHERE MaTrinhDo = 'TD02';
UPDATE TRINHDO
SET TenTrinhDo = N'thợ sửa bậc 3'
WHERE MaTrinhDo = 'TD03';

ALTER TABLE NHANVIEN
ALTER COLUMN TenNhanVien NVARCHAR(30);
